name: Main CI

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Pull repository
        uses: actions/checkout@v2.3.1

      - name: Restore NuGet packages
        run: nuget restore AutoDbdFlexerEx.sln

      - name: Build
        run: |
          msbuild AutoDbdFlexerEx.sln -p:Configuration=Release -p:OutDir=../build
          if ($? -eq $false) { Exit 1 }

      - name: Switch to solution direcotry
        run: cd AutoDbdFlexerEx

      - name: Delete build trash
        run: |
          rm build/AutoDbdFlexerEx.pdb
          rm build/Newtonsoft.Json.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AutoDbdFlexerEx
          path: build
